In [37]:
import os
import numpy as np
import torch

In [34]:
def calculate_precision_recall(predicted_labels, true_labels):
    predicted_set = set(tuple(pair) for pair in predicted_labels)
    true_set = set(tuple(pair) for pair in true_labels)

    TP = len(predicted_set.intersection(true_set))
    FP = len(predicted_set - true_set)
    FN = len(true_set - predicted_set)
    print(TP, FP, FN)

    precision = TP / (TP + FP) if TP + FP > 0 else 0
    recall = TP / (TP + FN) if TP + FN > 0 else 0

    return precision, recall

# 示例预测和标注的标签对
predicted_labels = [[0, 1], [1, 2], [2, 3]]
true_labels = [[0, 1], [2, 3], [1, 4], [3, 4], [4, 5],[2, 4], [1, 3]]

# 计算 Precision 和 Recall
precision, recall = calculate_precision_recall(predicted_labels, true_labels)

print("Precision:", precision)
print("Recall:", recall)


2 1 5
Precision: 0.6666666666666666
Recall: 0.2857142857142857


In [47]:
predicted_labels = [[0, 1], [1, 2], [2, 3]]
true_labels = [[0, 1], [2, 3], [1, 4], [3, 4], [4, 5],[2, 4], [1, 3], [-1, -1], [-1, -1]]

print(np.sum(true_labels, -1, keepdims=False) > 0)
print(true_labels[0])
true_labels = true_labels[np.sum(true_labels, -1, keepdims=False) > 0]

TP_edges = np.sum([e in true_labels for e in predicted_labels])
TP_FP = len(predicted_labels)
TP_FN = len(true_labels)
precision = TP_edges / TP_FP
recall = TP_edges / TP_FN
# print([e in true_labels for e in predicted_labels])

# 计算 Precision 和 Recall
# precision, recall = calculate_precision_recall(predicted_labels, true_labels)

print("Precision:", precision)
print("Recall:", recall)

[ True  True  True  True  True  True  True False False]
[0, 1]


TypeError: only integer scalar arrays can be converted to a scalar index

In [3]:
import numpy as np
from scipy.optimize import linear_sum_assignment

# 创建一个随机的权重矩阵
cost_matrix = np.array([[4, 1, 3],
                        [2, 0, 5],
                        [3, 2, 2]])

# 使用 linear_sum_assignment 求解最小权重匹配问题
row_indices, col_indices = linear_sum_assignment(cost_matrix)

print("Row indices:", row_indices)
print("Column indices:", col_indices)


Row indices: [0 1 2]
Column indices: [1 0 2]


In [28]:
import numpy as np
from scipy.spatial.distance import cdist

# Two sets of points with different lengths
point_set1 = np.array([[1, 2, 3], [7, 8, 9], [4, 5, 1], [7, 8, 9]])
point_set2 = np.array([[2, 3, 4], [5, 6, 4]])

# Calculate the distance matrix
distance_matrix = cdist(point_set1, point_set2)

print(distance_matrix)
row_indices, col_indices = linear_sum_assignment(distance_matrix)
print(row_indices, col_indices)
mask = distance_matrix[row_indices, col_indices]
print(mask)
print(mask < 6)
mask = mask < 6
print(row_indices[mask], col_indices[mask])
print(point_set1[row_indices[mask]])

[[1.73205081 5.74456265]
 [8.66025404 5.74456265]
 [4.12310563 3.31662479]
 [8.66025404 5.74456265]]
[0 2] [0 1]
[1.73205081 3.31662479]
[ True  True]
[0 2] [0 1]
[[1 2 3]
 [4 5 1]]


In [23]:
print(mask)

[ True False]
