In [10]:
from datasets import build_dataset

In [11]:
import yaml

In [12]:
from easydict import EasyDict

In [13]:
def cfg_from_yaml_file(cfg_file):
    with open(cfg_file, 'r') as f:
        try:
            new_config = yaml.load(f, Loader=yaml.FullLoader)
        except:
            new_config = yaml.load(f)

    cfg = EasyDict(new_config)
    return cfg

In [14]:
dataset_config = cfg_from_yaml_file('dataset_config.yaml')
print(dataset_config)

{'Building3D': {'root_dir': 'D:\\Supervised\\data\\Talinn', 'num_points': 2048, 'use_color': True, 'use_intensity': True, 'normalize': True, 'augment': False}}


In [15]:
building3D_dataset = build_dataset(dataset_config.Building3D)
# print(dir(building3D_dataset['train']))
print(building3D_dataset["test"].wireframe_files)

[]


In [16]:
from torch.utils.data import DataLoader

In [17]:
train_loader = DataLoader(building3D_dataset['train'], batch_size=1, shuffle=True, drop_last=True)
for batch in train_loader:
    print(batch)
    break

[5.38382990e+05 6.58749562e+06 1.20300000e+01 1.40625000e-01
 1.60156250e-01 1.83593750e-01 1.60156250e-01 3.61090000e+04]
D:\Supervised\data\Talinn\train\xyz\9520.xyz
[-3.4670779e-01  6.2810034e-01 -5.1261537e-02  1.4062500e-01
  1.6015625e-01  1.8359375e-01  1.6015625e-01  3.6109000e+04]
[[-0.4869085   0.6919541  -0.05423213]
 [-0.6887114   0.23137538  0.15103002]
 [-0.33347479  0.6224992  -0.05423213]
 [-0.32259604  0.64653045 -0.06500398]
 [ 0.5879478  -0.3465291   0.15103002]
 [ 0.8026603   0.1408682  -0.06637823]
 [-0.89501745 -0.23947825 -0.05624491]
 [ 0.38622257 -0.8044454  -0.05073405]
 [-0.33347479  0.6224992  -0.39111635]
 [-0.3897397   0.6600272  -0.39510027]
 [-0.32259604  0.64653045 -0.4007083 ]
 [-0.30506402  0.8529767  -0.47171092]
 [ 0.6471902   0.45180836 -0.48160827]
 [ 0.55835015  0.24775387 -0.4007083 ]]
tensor([0])


In [18]:
import numpy as np

# Assuming you have a point cloud represented as a NumPy array
point_cloud = np.array([[535152.7100, 6581069.1400, 48.8000], [535152.8800, 6581069.7400, 48.8400], [535152.6800, 6581067.5900, 49.1200]], dtype=np.float64)

# Calculate the mean and standard deviation along each axis
mean = np.mean(point_cloud, axis=0)
std = np.std(point_cloud, axis=0)

# Normalize the point cloud by subtracting the mean and dividing by the standard deviation
normalized_point_cloud = (point_cloud - mean) / std

# Print the normalized point cloud
print(normalized_point_cloud.dtype)
print(normalized_point_cloud)

float64
[[-0.52990782  0.34958143 -0.84292723]
 [ 1.40047065  1.01194625 -0.56195149]
 [-0.87056284 -1.36152768  1.40487872]]
