In [1]:
from datasets import build_dataset

In [2]:
import yaml

In [3]:
from easydict import EasyDict

In [4]:
def cfg_from_yaml_file(cfg_file):
    with open(cfg_file, 'r') as f:
        try:
            new_config = yaml.load(f, Loader=yaml.FullLoader)
        except:
            new_config = yaml.load(f)

    cfg = EasyDict(new_config)
    return cfg

In [5]:
dataset_config = cfg_from_yaml_file('dataset_config.yaml')
print(dataset_config)

{'Building3D': {'root_dir': 'E:\\Building3D\\clear data\\Entry-level', 'num_points': 2048, 'use_color': True, 'use_intensity': True, 'normalize': True, 'augment': False}}


In [6]:
building3D_dataset = build_dataset(dataset_config.Building3D)
# print(dir(building3D_dataset['train']))
print(building3D_dataset["test"].wireframe_files)

['E:\\Building3D\\clear data\\Entry-level\\test\\wireframe\\10033.obj', 'E:\\Building3D\\clear data\\Entry-level\\test\\wireframe\\10105.obj', 'E:\\Building3D\\clear data\\Entry-level\\test\\wireframe\\1022.obj', 'E:\\Building3D\\clear data\\Entry-level\\test\\wireframe\\1025.obj', 'E:\\Building3D\\clear data\\Entry-level\\test\\wireframe\\10256.obj', 'E:\\Building3D\\clear data\\Entry-level\\test\\wireframe\\10308.obj', 'E:\\Building3D\\clear data\\Entry-level\\test\\wireframe\\10443.obj', 'E:\\Building3D\\clear data\\Entry-level\\test\\wireframe\\10466.obj', 'E:\\Building3D\\clear data\\Entry-level\\test\\wireframe\\10476.obj', 'E:\\Building3D\\clear data\\Entry-level\\test\\wireframe\\10592.obj', 'E:\\Building3D\\clear data\\Entry-level\\test\\wireframe\\10643.obj', 'E:\\Building3D\\clear data\\Entry-level\\test\\wireframe\\10645.obj', 'E:\\Building3D\\clear data\\Entry-level\\test\\wireframe\\10646.obj', 'E:\\Building3D\\clear data\\Entry-level\\test\\wireframe\\10750.obj', 'E:\\Bu

In [7]:
from torch.utils.data import DataLoader

In [8]:
train_loader = DataLoader(building3D_dataset['train'], batch_size=1, shuffle=True, drop_last=True)
for batch in train_loader:
    print(batch)
    break

E:\Building3D\clear data\Entry-level\train\xyz\36634.xyz
[5.49612200e+05 6.59480001e+06 3.12900000e+01 3.59375000e-01
 4.53125000e-01 3.98437500e-01 3.82812500e-01 3.76600000e+04]
tensor([0])


In [9]:
import numpy as np

# Assuming you have a point cloud represented as a NumPy array
point_cloud = np.array([[535152.7100, 6581069.1400, 48.8000], [535152.8800, 6581069.7400, 48.8400], [535152.6800, 6581067.5900, 49.1200]], dtype=np.float64)

# Calculate the mean and standard deviation along each axis
mean = np.mean(point_cloud, axis=0)
std = np.std(point_cloud, axis=0)

# Normalize the point cloud by subtracting the mean and dividing by the standard deviation
normalized_point_cloud = (point_cloud - mean) / std

# Print the normalized point cloud
print(normalized_point_cloud.dtype)
print(normalized_point_cloud)

float64
[[-0.52990782  0.34958143 -0.84292723]
 [ 1.40047065  1.01194625 -0.56195149]
 [-0.87056284 -1.36152768  1.40487872]]
